language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t tim/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true tim/react-test npm test

after_success:
  - docker build -t two646/multi-client ./client
  - docker build -t two646/multi-nginx ./nginx
  - docker build -t two646/multi-server ./server
  - docker build -t two646/multi-worker ./worker
  # log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images  and push them to docker hub
  - docker push two646/multi-client
  - docker push two646/multi-nginx
  - docker push two646/multi-server
  - docker push two646/multi-worker